esphome:
  name: 7b-test
  includes:
    - custom/panelly_helpers.h
  on_boot:
    priority: -100
    then:
      - logger.log:
          level: DEBUG
          format: "BOOT LOG"

packages:
  colors: !include colors.yaml
  theme: !include theme.yaml

api:
  reboot_timeout: 600s
  on_client_connected:
    then:
      - script.execute: update_api_state_label
      - script.execute: update_entrance_light_button
  on_client_disconnected:
    then:
      - script.execute: update_api_state_label

globals:
  - id: click_counter
    type: int16_t
    restore_value: no
    initial_value: "0"

logger:
  level: DEBUG
  hardware_uart: UART0
  baud_rate: 115200

esp32:
  variant: esp32p4
  engineering_sample: true
  flash_size: 32MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf

psram:
  mode: hex
  speed: 200MHz

preferences:
  flash_write_interval: 5min

esp_ldo:
  - voltage: 2.5V
    channel: 3

# Comms chip
esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: true
  on_connect:
    then:
      - lvgl.label.update:
          id: wifi_state_label
          text: "WIFI: connected"
  on_disconnect:
    then:
      - lvgl.label.update:
          id: wifi_state_label
          text: "WIFI: disconnected"

#   # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "7B-Test Fallback Hotspot"
#     password: "aaa123456"

script:
  - id: update_entrance_light_button
    then:
      - if:
          condition:
            binary_sensor.is_on: lights_entrance
          then:
            - lvgl.label.update:
                id: entrance_light_toggle_lbl
                text: Toggle off
            - lvgl.button.update:
                id: entrance_light_toggle
                bg_color: ${button_light_on_bg}
          else:
            - lvgl.label.update:
                id: entrance_light_toggle_lbl
                text: Toggle on
            - lvgl.button.update:
                id: entrance_light_toggle
                bg_color: ${button_default_bg}

  - id: update_api_state_label
    mode: restart
    then:
      - delay: 1000ms
      - if:
          condition:
            api.connected:
              state_subscription_only: true
          then:
            - lvgl.label.update:
                id: api_state_label
                text: "API: connected"
          else:
            - lvgl.label.update:
                id: api_state_label
                text: "API: disconnected"

binary_sensor:
  - platform: homeassistant
    id: lights_entrance
    entity_id: light.lights_entrance
    trigger_on_initial_state: true
    on_state:
      then:
        # - logger.log:
        #     level: DEBUG
        #     format: "lights_entrance state from HA: %s"
        #     args: ['id(lights_entrance).state ? "ON" : "OFF"']
        - script.execute: update_entrance_light_button

# -------------------------------------------
# Touchscreen gt911 i2c
# -------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO07
    scl: GPIO08
    frequency: 400kHz

touchscreen:
  - platform: gt911
    id: embedded_touch
    i2c_id: bus_a
    reset_pin: GPIO23
    update_interval: 50ms
    transform:
      swap_xy: false
      mirror_x: true
      mirror_y: true

# -------------------------------------------
# Backlight
# -------------------------------------------
output:
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO32
    inverted: true
    frequency: 1000Hz

light: # wthats that???
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    id: embedded_display
    model: WAVESHARE-ESP32-P4-WIFI6-TOUCH-LCD-7B
    update_interval: never
    auto_clear_enabled: false

# LVGL settings required for this display
lvgl:
  buffer_size: 100 %
  byte_order: little_endian
  rotation: 180
  touchscreens:
    - touchscreen_id: embedded_touch

  on_boot:
    then:
      - script.execute: update_api_state_label

  widgets:
    # Background
    - obj:
        x: 0
        y: 0
        width: 1024
        height: 600
        bg_color: ${theme_bg}
        bg_opa: COVER
        border_width: 0
        radius: 0

    - button:
        id: entrance_light_toggle
        align: CENTER
        y: 0
        x: -300
        width: 150
        height: 90
        bg_color: ${button_default_bg}
        bg_opa: COVER
        radius: 16
        widgets:
          - label:
              id: entrance_light_toggle_lbl
              align: CENTER
              text: "Toggle ..."
              text_font: montserrat_20
        on_click:
          then:
            - if:
                condition:
                  binary_sensor.is_on: lights_entrance
                then:
                  - homeassistant.action:
                      action: scene.turn_on
                      data:
                        entity_id: scene.lights_entrance_12_off
                else:
                  - homeassistant.action:
                      action: scene.turn_on
                      data:
                        entity_id: scene.lights_entrance_11_on
    # Test labels
    - obj:
        x: 10
        y: 10
        width: SIZE_CONTENT
        height: SIZE_CONTENT
        bg_opa: TRANSP
        border_width: 0
        pad_all: 0
        layout:
          type: FLEX
          pad_column: 32
          flex_flow: ROW
          flex_align_main: START
          flex_align_cross: CENTER
          flex_align_track: CENTER
        widgets:
          - label:
              text: "DISPLAY: ok"
              text_color: 0xFFFFFF
              text_font: montserrat_20
          - label:
              id: wifi_state_label
              text: "WIFI: disconnected"
              text_color: 0xFFFFFF
              text_font: montserrat_20
          - label:
              id: api_state_label
              text: "API: disconnected"
              text_color: 0xFFFFFF
              text_font: montserrat_20
