esphome:
  name: 7b-test
  on_boot:
    priority: -100
    then:
      - logger.log:
          level: INFO
          format: "BOOT LOG"

image:
  - file: "avatar_144.png"
    id: channel_avatar_img
    type: rgb565
    transparency: alpha_channel
    resize: 96x96

globals:
  - id: subscribed
    type: bool
    restore_value: no
    initial_value: "false"
  - id: notifications_enabled
    type: bool
    restore_value: no
    initial_value: "false"

logger:
  level: DEBUG
  hardware_uart: UART0
  baud_rate: 115200

esp32:
  variant: esp32p4
  engineering_sample: true
  flash_size: 32MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf

psram:
  mode: hex
  speed: 200MHz

preferences:
  flash_write_interval: 5min

esp_ldo:
  - voltage: 2.5V
    channel: 3

# Comms chip
esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

# wifi:
#   ssid: "dummyssid"
#   password: "njnjnjn00000111"

#   # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "7B-Test Fallback Hotspot"
#     password: "aaa123456"

# -------------------------------------------
# Touchscreen gt911 i2c
# -------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO07
    scl: GPIO08
    frequency: 400kHz

touchscreen:
  - platform: gt911
    id: embedded_touch
    i2c_id: bus_a
    reset_pin: GPIO23
    update_interval: 50ms
    transform:
      swap_xy: false
      mirror_x: true
      mirror_y: true

# -------------------------------------------
# Backlight
# -------------------------------------------
output:
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO32
    inverted: true
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    id: embedded_display
    model: WAVESHARE-ESP32-P4-WIFI6-TOUCH-LCD-7B
    update_interval: never
    auto_clear_enabled: false

# LVGL settings required for this display
lvgl:
  buffer_size: 100 %
  byte_order: little_endian
  rotation: 180
  touchscreens:
    - touchscreen_id: embedded_touch

  widgets:
    # Background
    - obj:
        x: 0
        y: 0
        width: 1024
        height: 600
        bg_color: 0x0F0F0F
        bg_opa: COVER
        border_width: 0
        radius: 0

    - obj:
        id: subscribe
        align: CENTER
        scrollable: false
        width: 800
        height: 128
        bg_opa: TRANSP
        border_width: 0
        radius: 0
        widgets:
          - image:
              id: avatar
              x: 0
              y: 0
              width: 96
              height: 96
              radius: 48
              src: channel_avatar_img
              clip_corner: true

          - button:
              id: sub_btn
              x: 160
              y: 0
              width: 360
              height: 96
              bg_color: 0xFF0000
              bg_opa: COVER
              border_width: 0
              radius: 48
              shadow_width: 0
              widgets:
                - label:
                    id: sub_btn_label
                    align: CENTER
                    text: "Subscribe"
                    text_color: 0xFFFFFF
                    text_font: montserrat_48
              on_click:
                then:
                  - lambda: |-
                      id(subscribed) = !id(subscribed);

                      if (!id(subscribed)) {
                        id(notifications_enabled) = false;
                      }
                  - if:
                      condition:
                        lambda: return id(subscribed);
                      then:
                        - lvgl.button.update:
                            id: sub_btn
                            bg_color: 0x272727
                            text_color: 0xF1F1F1
                        - lvgl.label.update:
                            id: sub_btn_label
                            text: "Subscribed"
                            bg_color: 0x272727
                            text_color: 0xF1F1F1

                        - lvgl.widget.update:
                            id: notifications_btn
                            hidden: false

          - button:
              id: notifications_btn
              x: 584
              y: 0
              width: 96
              height: 96
              bg_color: 0xF1F1F1
              bg_opa: COVER
              border_width: 0
              radius: 48
              hidden: true
              shadow_width: 0
              widgets:
                - label:
                    id: notifications_icon
                    align: CENTER
                    text: "\uF0F3"
                    text_color: 0x272727
                    bg_color: 0xF1F1F1
                    text_font: montserrat_48

              on_click:
                then:
                  - if:
                      condition:
                        lambda: return id(subscribed);
                      then:
                        - lambda: id(notifications_enabled) = !id(notifications_enabled);
                        - if:
                            condition:
                              lambda: return id(notifications_enabled);
                            then:
                              - lvgl.widget.update:
                                  id: notifications_btn
                                  bg_color: 0x272727
                                  text_color: 0xF1F1F1

                              - lvgl.label.update:
                                  id: notifications_icon
                                  text_color: 0xF1F1F1

                            else:
                              - lvgl.widget.update:
                                  id: notifications_btn
                                  bg_color: 0x272727
                                  border_color: 0x3F3F3F

                              - lvgl.label.update:
                                  id: notifications_icon
                                  text_color: 0xF1F1F1
